{
 "title": "Sales Monitoring",
 "tags": [
  "backend",
  "monitoring",
  "sales"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (finpos_http_requests_total{job=\"backend\", endpoint=~\".*sales-invoice.*\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (finpos_http_requests_total{job=\"backend\", endpoint=\"/api/v1/sales-invoice\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(finpos_http_requests_total{endpoint=~\".*sales-invoice.*\", status!~\"2.*\"}[1h])",
     "legendFormat": "{{status}} {{service}} - {{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Sales Invoice - List",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(finpos_http_requests_total{job=\"backend\", endpoint=\"/api/v1/sales-invoice\", method=\"GET\", status=~\"200\"}[10m])",
     "legendFormat": "{{status}} {{service}} - {{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Sales Invoice - List - ResponTime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(finpos_http_request_duration_seconds_sum{method=\"GET\", job=\"backend\", endpoint=\"/api/v1/sales-invoice\"}[$__rate_interval])",
     "legendFormat": "{{status}} {{service}} - {{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Sales Invoice - Create",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "increase(finpos_http_requests_total{job=\"backend\", method=\"POST\", endpoint=\"/api/v1/sales-invoice\", status=~\"200\"}[10m])",
     "legendFormat": "{{status}} {{service}} - {{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Sales Invoice - Create - Respon Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(finpos_http_request_duration_seconds_sum{endpoint=\"/api/v1/sales-invoice\", method=\"POST\"}[$__rate_interval])",
     "legendFormat": "{{service}} - {{method}} {{endpoint}}"
    }
   ]
  }
 ]
}